//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pokeBbyzApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        public int ID { get; set; }
        public int Species { get; set; }
        public bool Gender { get; set; }
        public string Nickname { get; set; }
        public decimal Growthrate { get; set; }
        public int Attack { get; set; }
        public int Defense { get; set; }
        public int HP { get; set; }
        public int Speed { get; set; }
        public int Happiness { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int OwnerID { get; set; }
    
        public virtual PokemonSpecy PokemonSpecy { get; set; }
        public virtual User User { get; set; }
    }
}
